version: '3'

services:
    web:
      image: lucavelozo/web2-velozo:latest
      ports:
        - "81:80"
      volumes:
        - ./home/LV/UTN-FRA_SO_Examenes/202411/docker/web/file:/usr/share/nginx/html/file/

